#!/bin/sh

# Copyright (C) 2012 Lauri Kasanen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Derives the option denominator from getopt_long and proves that the binary,
# the canonical man source, and the generated man page expose the same public
# names and that the tracked man page equals a fresh AsciiDoc rendering.  The
# self-test deletes one option heading and changes one generated byte; both
# mutations must fail.

set -eu

repo_root=$(git rev-parse --show-toplevel)
scratch=$(mktemp -d)

cleanup() {
	rm -rf -- "$scratch"
}
trap cleanup 0 1 2 15

export LC_ALL=C

compare_sets() {
	expected=$1
	actual=$2
	label=$3

	if ! cmp -s "$expected" "$actual"; then
		echo "$label option set differs from getopt_long" >&2
		diff -u "$expected" "$actual" >&2 || true
		return 1
	fi
}

verify_cli_docs() {
	binary=$1
	source_file=$2
	man_source=$3
	man_page=$4
	inventory=$scratch/inventory
	expected_long=$scratch/expected-long
	expected_short=$scratch/expected-short
	actual_short=$scratch/actual-short
	help_output=$scratch/help
	help_long=$scratch/help-long
	man_source_long=$scratch/man-source-long
	generated_man_dir=$scratch/generated-man
	generated_man=$generated_man_dir/$(basename "${man_source%.asc}").1
	man_diagnostics=$scratch/man-diagnostics

	[ -x "$binary" ] || {
		echo "binary is unavailable or not executable: $binary" >&2
		return 1
	}
	for input_file in "$source_file" "$man_source" "$man_page"; do
		[ -f "$input_file" ] || {
			echo "input is unavailable: $input_file" >&2
			return 1
		}
	done

	mkdir -p "$generated_man_dir"
	: > "$man_diagnostics"
	if ! a2x -f manpage -D "$generated_man_dir" "$man_source" \
		2> "$man_diagnostics"; then
		cat "$man_diagnostics" >&2
		return 1
	fi
	if [ -s "$man_diagnostics" ]; then
		cat "$man_diagnostics" >&2
		return 1
	fi
	if ! cmp -s "$generated_man" "$man_page"; then
		echo "tracked man page differs from the canonical AsciiDoc rendering" >&2
		diff -u "$man_page" "$generated_man" >&2 || true
		return 1
	fi

	awk '
	function trim(value) {
		sub(/^[[:space:]]+/, "", value)
		sub(/[[:space:]}]+$/, "", value)
		return value
	}
	/const struct option opts\[\] = \{/ {
		in_options = 1
		next
	}
	in_options && /^[[:space:]]*\{(0|NULL),/ {
		exit
	}
	in_options && /^[[:space:]]*\{"/ {
		split($0, quoted, "\"")
		split(quoted[3], fields, ",")
		argument = trim(fields[2])
		flag_pointer = trim(fields[3])
		value = trim(fields[4])

		if (argument == "required_argument" || argument == "1")
			required = "arg"
		else if (argument == "no_argument" || argument == "0")
			required = "flag"
		else
			required = "invalid"

		if (flag_pointer != "NULL" && flag_pointer != "0")
			required = "invalid"

		short_name = length(value) == 3 && substr(value, 1, 1) == "\047" && \
			substr(value, 3, 1) == "\047" ? substr(value, 2, 1) : "-"
		print quoted[2] "|" required "|" short_name
	}
	' "$source_file" > "$inventory"

	[ -s "$inventory" ] || {
		echo "getopt_long option denominator is empty" >&2
		return 1
	}
	if grep -Fq '|invalid|' "$inventory"; then
		echo "getopt_long contains an unsupported option initializer" >&2
		return 1
	fi

	if cut -d '|' -f1 "$inventory" | sort | uniq -d | grep -q .; then
		echo "getopt_long contains duplicate long options" >&2
		return 1
	fi
	if cut -d '|' -f3 "$inventory" | grep -v '^-$' |
		sort | uniq -d | grep -q .; then
		echo "getopt_long contains duplicate short options" >&2
		return 1
	fi

	cut -d '|' -f1 "$inventory" | sort > "$expected_long"
	cut -d '|' -f3 "$inventory" | grep -v '^-$' | sort > "$expected_short"

	optstring=$(sed -n \
		's/.*getopt_long(argc, argv, "\([^"]*\)".*/\1/p' "$source_file")
	[ -n "$optstring" ] || {
		echo "getopt short-option string is unavailable" >&2
		return 1
	}
	option_letters=${optstring#+}
	option_letters=${option_letters#-}
	printf '%s' "$option_letters" | tr -d ':' | fold -w 1 | sort > "$actual_short"
	compare_sets "$expected_short" "$actual_short" "getopt short" || return 1

	"$binary" --help > "$help_output"
	awk '
	/^[[:space:]]*-/ {
		for (field = 1; field <= NF; field++) {
			if ($field ~ /^--[a-z][a-z-]*$/) {
				name = $field
				sub(/^--/, "", name)
				print name
				break
			}
		}
	}
	' "$help_output" | sort -u > "$help_long"
	compare_sets "$expected_long" "$help_long" "--help" || return 1

	sed -n \
		's/^\*[^:]*--\([a-z][a-z-]*\)[^:]*\*::$/\1/p' \
		"$man_source" | sort -u > "$man_source_long"
	compare_sets "$expected_long" "$man_source_long" "man source" || return 1

	while IFS='|' read -r long_name argument_kind short_name; do
		if [ "$short_name" = "-" ]; then
			help_pattern="--$long_name"
			man_flag="*--$long_name*::"
			man_argument="^\*--$long_name '[^']+'\*::$"
		else
			help_pattern="-$short_name --$long_name"
			man_flag="*-$short_name, --$long_name*::"
			man_argument="^\*-$short_name, --$long_name '[^']+'\*::$"
		fi

		grep -Fq -- "$help_pattern" "$help_output" || {
			echo "--help lacks the binding $help_pattern" >&2
			return 1
		}

		case "$argument_kind" in
			arg)
				if [ "$short_name" != "-" ]; then
					case "$optstring" in
						*"$short_name":*) ;;
						*)
							echo "-$short_name lacks its getopt argument marker" >&2
							return 1
							;;
					esac
				fi
				grep -Eq "$man_argument" "$man_source" || {
					echo "man source lacks an argument for --$long_name" >&2
					return 1
				}
				;;
			flag)
				if [ "$short_name" != "-" ]; then
					case "$optstring" in
						*"$short_name":*)
							echo "-$short_name has an unexpected getopt argument marker" >&2
							return 1
							;;
					esac
				fi
				grep -Fxq "$man_flag" "$man_source" || {
					echo "man source gives --$long_name an argument" >&2
					return 1
				}
				;;
			*)
				echo "unknown option kind: $argument_kind" >&2
				return 1
				;;
		esac

		escaped_long=$(printf '%s\n' "$long_name" | sed 's/-/\\-/g')
		grep -Fq -- "\-\-$escaped_long" "$man_page" || {
			echo "generated man page lacks --$long_name" >&2
			return 1
		}
	done < "$inventory"

	if grep -Fq '[FIXME:' "$man_page"; then
		echo "generated man page retains an AsciiDoc FIXME marker" >&2
		return 1
	fi

	for operand_order in before after; do
		case "$operand_order" in
			before) set -- unexpected-operand --help ;;
			after) set -- --help unexpected-operand ;;
		esac
		if "$binary" "$@" > "$scratch/operand-out" \
			2> "$scratch/operand-err"; then
			echo "$operand_order-option operand was accepted" >&2
			return 1
		fi
		grep -Fq "Unexpected operand 'unexpected-operand'" \
			"$scratch/operand-err" || {
			echo "$operand_order-option operand lacks its diagnostic" >&2
			return 1
		}
	done
}

cd "$repo_root"

verify_cli_docs ./radeontop radeontop.c radeontop.asc radeontop.1

if [ "${1:-}" = "--self-test" ]; then
	bad_man_source=$scratch/missing-dither-seed.asc
	sed '/^\*--dither-seed /d' radeontop.asc > "$bad_man_source"

	if verify_cli_docs ./radeontop radeontop.c "$bad_man_source" radeontop.1 \
		>/dev/null 2>&1; then
		echo "negative control accepted a missing --dither-seed heading" >&2
		exit 1
	fi

	bad_man_page=$scratch/stale-radeontop.1
	cp radeontop.1 "$bad_man_page"
	printf '\n' >> "$bad_man_page"
	if verify_cli_docs ./radeontop radeontop.c radeontop.asc "$bad_man_page" \
		>/dev/null 2>&1; then
		echo "negative control accepted a stale generated man page" >&2
		exit 1
	fi
	printf '%s\n' \
		"CLI documentation verifier: known-good accepted, two known-bad inputs rejected"
elif [ "$#" -ne 0 ]; then
	echo "usage: $0 [--self-test]" >&2
	exit 2
else
	printf '%s\n' "CLI documentation verifier: option surfaces agree"
fi
